<?php
// Generated at: 2025-02-27 07:24:29
// Generated by: niloc95

class MigrationInstaller
{
    private $basePath;
    private $migrations = [
        'CreateUsersTable' => '2014_10_12_000000_create_users_table.php',
        'CreatePasswordResetTokensTable' => '2014_10_12_100000_create_password_reset_tokens_table.php',
        'CreateFailedJobsTable' => '2019_08_19_000000_create_failed_jobs_table.php',
        'CreatePersonalAccessTokensTable' => '2019_12_14_000001_create_personal_access_tokens_table.php'
    ];

    public function __construct()
    {
        $this->basePath = dirname(__DIR__) . '/database/migrations';
    }

    public function install()
    {
        echo "Installing Laravel migrations...\n";
        
        // Create migrations directory if it doesn't exist
        if (!is_dir($this->basePath)) {
            mkdir($this->basePath, 0755, true);
            echo "Created migrations directory\n";
        }

        // Install each migration
        foreach ($this->migrations as $class => $file) {
            $path = $this->basePath . '/' . $file;
            if (file_exists($path)) {
                echo "Migration {$file} already exists, skipping...\n";
                continue;
            }

            // Copy migration file
            if (copy(__DIR__ . '/templates/' . $file, $path)) {
                echo "✅ Installed {$file}\n";
            } else {
                echo "❌ Failed to install {$file}\n";
            }
        }

        echo "\nRunning migrations...\n";
        system('php ../artisan migrate:fresh');
    }
}

// Run installer
$installer = new MigrationInstaller();
$installer->install();