<?php
// Generated at: 2025-02-27 07:11:39
// Generated by: niloc95

class MigrationVerifier
{
    private $basePath;
    private $requiredMigrations = [
        '2014_10_12_000000_create_users_table.php',
        '2014_10_12_100000_create_password_reset_tokens_table.php',
        '2019_08_19_000000_create_failed_jobs_table.php',
        '2019_12_14_000001_create_personal_access_tokens_table.php'
    ];

    public function __construct()
    {
        $this->basePath = dirname(__DIR__) . '/database/migrations';
    }

    public function verify()
    {
        echo "Verifying Laravel migrations...\n";
        
        $missing = [];
        foreach ($this->requiredMigrations as $migration) {
            $path = $this->basePath . '/' . $migration;
            if (!file_exists($path)) {
                $missing[] = $migration;
            }
        }

        if (empty($missing)) {
            echo "✅ All required migrations are present.\n";
            return true;
        } else {
            echo "❌ Missing migrations:\n";
            foreach ($missing as $migration) {
                echo "   - {$migration}\n";
            }
            return false;
        }
    }
}

// Run verification
$verifier = new MigrationVerifier();
$verifier->verify();