<?php
// Generated at: 2025-02-27 08:09:34
// Generated by: niloc95

class GitVerifier
{
    private $basePath;
    private $requiredFiles = [
        '.gitignore',
        'README.md',
        'LICENSE'
    ];

    public function __construct()
    {
        $this->basePath = dirname(__DIR__);
    }

    public function verify()
    {
        echo "Verifying Git setup...\n";
        
        // Check Git initialization
        if (!is_dir($this->basePath . '/.git')) {
            echo "❌ Git not initialized\n";
            return false;
        }
        echo "✅ Git initialized\n";

        // Verify required files
        foreach ($this->requiredFiles as $file) {
            $path = $this->basePath . '/' . $file;
            if (!file_exists($path)) {
                echo "❌ Missing file: {$file}\n";
            } else {
                echo "✅ Found file: {$file}\n";
            }
        }

        // Check remote
        $remote = shell_exec('git remote -v');
        if (strpos($remote, 'github.com/niloc95/webSchedulr-Reborn') === false) {
            echo "❌ GitHub remote not configured correctly\n";
        } else {
            echo "✅ GitHub remote configured\n";
        }

        // Check current branch
        $branch = trim(shell_exec('git branch --show-current'));
        echo "Current branch: {$branch}\n";
    }
}

// Run verification
$verifier = new GitVerifier();
$verifier->verify();